server:
  port: 8890
spring:
  application:
    name: module-resource
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/brownie
    username: root
    password: 159357
  jackson:
    # 返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
